export const  Barangays = [
    { title: "Bagahabag" },
    { title: "Bangaan" },
    { title: "Bangar" },
    { title: "Bascaran" },
    { title: "Communal" },
    { title: "Concepcion" },
    { title: "Curifang" },
    { title: "Dadap" },
    { title: "Lactawan" },
    { title: "Osmeña" },
    { title: "PD Galima" },
    { title: "Poblacion North" },
    { title: "Poblacion South" },
    { title: "Quezon" },
    { title: "Quirino" },
    { title: "Roxas" },
    { title: "San Juan" },
    { title: "San Luis" },
    { title: "Tucal" },
    { title: "Uddiawan" },
    { title: "Wacal" },
];