import { useEffect, useState } from "react";
import { AdminResponsiveContainer } from "../../ui/form/AdminResponsiveContainer";
import { PaginationUI } from "../../ui/form/PaginationUI";
import { TableUI } from "../../ui/form/TableUI";
import { useRenderedServices } from "../../hooks/useRenderedServices";
import { Search } from "lucide-react";
import { RenderedServiceSummary } from "./renderContent/RenderedServiceSummary";

type RenderedService = {
    _id: string;
    generatedBy: string;
    generatedByUser: {
        firstName: string;
        lastName: string;
    } | null;
    selectedService: string[];
    createdAt: string;
};

type RenderedServiceResponse = {
    data: RenderedService[];
    serviceCounts: Record<string, number>;
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

const RenderedService = () => {
    const [dateFrom, setDateFrom] = useState(() => new Date().toISOString().split("T")[0]);
    const [dateTo, setDateTo] = useState(() => new Date().toISOString().split("T")[0]);
    const [page, setPage] = useState(1);
    const [renderedServices, setRenderedServices] =
        useState<RenderedServiceResponse | null>(null);

    const { handleGetRenderedServiceByDate } = useRenderedServices();

    useEffect(() => {
        if (!dateFrom || !dateTo) return;

        const fetchData = async () => {
            const result = await handleGetRenderedServiceByDate({
                selectedDateFrom: dateFrom,
                selectedDateTo: dateTo,
                page,
                limit: 10,
            });

            if (result) setRenderedServices(result);
        };

        fetchData();
    }, [dateFrom, dateTo, page, handleGetRenderedServiceByDate]);

    const data = renderedServices?.data || [];
    const serviceCounts = renderedServices?.serviceCounts || {};

    const formatDate = (date: string) =>
        new Date(date).toLocaleString("en-PH", {
            year: "numeric",
            month: "long",
            day: "numeric",
            hour: "numeric",
            minute: "2-digit",
            second: "2-digit",
            hour12: true,
        });

    return (
        <AdminResponsiveContainer>
            <div className="flex w-full flex-col leading-none">
                <div className="border-b border-gray-300 py-3">
                    <h1 className="text-xl font-semibold text-gray-900">
                        Rendered Services
                    </h1>

                    <p className="mt-1 text-sm text-gray-500">
                        Overview of services currently rendered, including their total counts.
                    </p>
                </div>
            </div>

            {/* Date Filter */}
            <div className="flex gap-4">
                <div>
                    <label className="mb-1 block text-sm font-medium">
                        Start Date
                    </label>

                    <input
                        type="date"
                        value={dateFrom}
                        onChange={(e) => {
                            setDateFrom(e.target.value);
                            setPage(1);
                        }}
                        className="w-96 rounded-lg border border-gray-300 px-3 py-2 text-sm"
                    />
                </div>

                <div>
                    <label className="mb-1 block text-sm font-medium">
                        End Date
                    </label>

                    <input
                        type="date"
                        value={dateTo}
                        onChange={(e) => {
                            setDateTo(e.target.value);
                            setPage(1);
                        }}
                        className="w-96 rounded-lg border border-gray-300 px-3 py-2 text-sm"
                    />
                </div>
            </div>

            <RenderedServiceSummary serviceCounts={serviceCounts} />

            {/* Rendered Services */}
            <TableUI>
                <thead>
                    <tr>
                        <th className="px-4 py-3">
                            Generated By
                        </th>
                        <th className="px-4 py-3">
                            Service
                        </th>
                        <th className="px-4 py-3">
                            Date & Time Rendered
                        </th>
                    </tr>
                </thead>

                <tbody>
                    {data.length > 0 ? (
                        data.map((item) =>
                            item.selectedService.map((service) => (
                                <tr
                                    key={`${item._id}-${service}`}
                                    className="border-t"
                                >
                                    <td className="capitalize">
                                        {item.generatedByUser
                                            ? `${item.generatedByUser.firstName} ${item.generatedByUser.lastName}`.replaceAll(
                                                  "_",
                                                  " "
                                              )
                                            : "Unknown"}
                                    </td>

                                    <td>
                                        {service.replaceAll("_", " ")}
                                    </td>

                                    <td>
                                        {formatDate(item.createdAt)}
                                    </td>
                                </tr>
                            ))
                        )
                    ) : (
                        <tr>
                            <td colSpan={3} className="py-12">
                                <div className="m-9 flex flex-col items-center justify-center text-center">
                                    <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-gray-100">
                                        <Search
                                            size={22}
                                            className="text-gray-400"
                                        />
                                    </div>

                                    <p className="text-sm font-medium text-gray-700">
                                        No rendered services found
                                    </p>

                                    <p className="mt-1 text-xs text-gray-400">
                                        Try changing the date filter or check back later.
                                    </p>
                                </div>
                            </td>
                        </tr>
                    )}
                </tbody>
            </TableUI>

            {/* Pagination */}
            {renderedServices &&
                renderedServices.totalPages > 1 && (
                    <PaginationUI
                        currentPage={renderedServices.page}
                        totalPages={renderedServices.totalPages}
                        onPageChange={setPage}
                    />
                )}
        </AdminResponsiveContainer>
    );
};

export default RenderedService;
